# Generated by Django 4.2.28 on 2026-02-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemporaryIntakeCredential",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("login_id", models.CharField(max_length=150, unique=True)),
                ("password_hash", models.CharField(max_length=255)),
                ("form_type", models.CharField(choices=[("business", "Business"), ("individual", "Individual")], max_length=20)),
                ("client_email", models.EmailField(max_length=254)),
                ("created_by_login_id", models.CharField(max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
