# Generated by Django 4.2.28 on 2026-02-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_temporaryintakecredential'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessintakesubmission',
            old_name='payroll_id_country',
            new_name='payroll_id_county',
        ),
        migrations.AddField(
            model_name='businessintakesubmission',
            name='bank_account_type2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='businessintakesubmission',
            name='bank_contact_name2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='businessintakesubmission',
            name='bank_contact_phone2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='businessintakesubmission',
            name='bank_name2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
