# Generated by Django 4.2.28 on 2026-02-21 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_payroll_id_country_businessintakesubmission_payroll_id_county_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessintakesubmission',
            name='fiscal_year_end',
        ),
        migrations.AddField(
            model_name='businessintakesubmission',
            name='business_structure',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='businessintakesubmission',
            name='business_type',
            field=models.CharField(max_length=25),
        ),
    ]
