# Generated by Django 4.2.28 on 2026-02-21 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_businessintakesubmission_fiscal_year_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessintakesubmission',
            name='fiscal_year_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
