# Generated by Django 4.2.28 on 2026-02-21 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_businessintakesubmission_fiscal_year_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessintakesubmission',
            name='fin_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
