# Generated by Django 4.2.28 on 2026-04-01 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_businessintakesubmission_fin_number'),
    ]

    operations = [
    ]
