# Generic GraphQL query python interface, structure generated by OpenAI GPT
import json
import argparse
import requests
from pathlib import Path
from typing import Dict, Any, Optional

# Default location of the config file (same folder as this script)
CONFIG_PATH = Path("config.json")


class MondayAPIError(RuntimeError):
    """
    Custom exception type for monday.com API / GraphQL errors.
    We raise this when the HTTP request fails or monday returns GraphQL errors.
    """
    pass


def load_config(config_path: Path = CONFIG_PATH) -> Dict[str, Any]:
    """
    Reads config.json from disk and returns it as a Python dictionary.

    Why this exists:
    - Keeps API tokens, board IDs, column IDs, and defaults out of the terminal
    - Lets you change settings without touching code

    Raises:
    - FileNotFoundError if config.json does not exist
    - json.JSONDecodeError if config.json is not valid JSON
    """
    if not config_path.exists():
        raise FileNotFoundError(
            f"{config_path} not found. Create it from config.example.json."
        )

    with open(config_path, "r", encoding="utf-8") as f:
        return json.load(f)


def monday_request(
    query: str,
    variables: Optional[Dict[str, Any]],
    config: Dict[str, Any],
    timeout_s: int = 30,
) -> Dict[str, Any]:
    """
    Sends a GraphQL query/mutation to monday.com and returns the decoded JSON response.

    How it works:
    - Builds headers containing the monday API token (Authorization) and API version header
    - POSTs to monday's GraphQL endpoint with {"query": ..., "variables": ...}
    - Checks for HTTP errors (e.g. 401, 403, 500)
    - Checks for GraphQL errors in the returned JSON payload

    Returns:
    - The JSON-decoded response dictionary from monday

    Raises:
    - MondayAPIError for HTTP failures or GraphQL errors
    """
    monday_cfg = config["monday"]
    api_url = monday_cfg.get("api_url", "https://api.monday.com/v2")
    api_version = monday_cfg.get("api_version", "2024-04")
    api_token = monday_cfg.get("api_token")

    if not api_token:
        raise MondayAPIError("Missing monday.api_token in config.json")

    headers = {
        "Authorization": api_token,
        "Content-Type": "application/json",
        "API-Version": api_version,
    }

    payload: Dict[str, Any] = {"query": query}
    if variables is not None:
        payload["variables"] = variables

    resp = requests.post(api_url, headers=headers, json=payload, timeout=timeout_s)

    # HTTP-level problems (bad token, forbidden, etc.)
    if not resp.ok:
        raise MondayAPIError(f"HTTP {resp.status_code}: {resp.text}")

    data = resp.json()

    # GraphQL-level problems (bad mutation, wrong IDs, etc.)
    if "errors" in data and data["errors"]:
        raise MondayAPIError("GraphQL errors:\n" + json.dumps(data["errors"], indent=2))

    return data


def create_item(board_id: int, group_id: str, item_name: str, config: Dict[str, Any]) -> int:
    """
    Creates a new item (row) in the configured monday board/group.

    Inputs:
    - board_id: the monday board to create the item in
    - group_id: the group within that board (often "topics" or a custom group ID)
    - item_name: the name/title of the item (ex: Client name)

    Returns:
    - item_id (int) of the newly created item
    """
    mutation = """
    mutation ($board_id: ID!, $group_id: String!, $item_name: String!) {
      create_item(board_id: $board_id, group_id: $group_id, item_name: $item_name) {
        id
      }
    }
    """

    variables = {"board_id": board_id, "group_id": group_id, "item_name": item_name}
    result = monday_request(mutation, variables, config)

    return int(result["data"]["create_item"]["id"])


def update_columns(
    board_id: int,
    item_id: int,
    column_values: Dict[str, Any],
    config: Dict[str, Any],
) -> int:
    """
    Updates multiple column values on an existing item.

    IMPORTANT monday detail:
    - The column_values parameter must be passed as a JSON *string* (not a dict)

    Inputs:
    - board_id: the board containing the item
    - item_id: the item to update
    - column_values: dictionary keyed by monday column ID -> value

    Returns:
    - item_id of the updated item (monday echoes it back)
    """
    mutation = """
    mutation ($board_id: ID!, $item_id: ID!, $column_values: JSON!) {
      change_multiple_column_values(
        board_id: $board_id,
        item_id: $item_id,
        column_values: $column_values
      ) {
        id
      }
    }
    """

    variables = {
        "board_id": board_id,
        "item_id": item_id,
        # monday requires this to be a JSON string
        "column_values": json.dumps(column_values),
    }

    result = monday_request(mutation, variables, config)
    return int(result["data"]["change_multiple_column_values"]["id"])


def build_column_values(
    args: argparse.Namespace,
    config: Dict[str, Any],
) -> Dict[str, Any]:
    """
    Builds the monday column_values dictionary using:
    - the CLI arguments the user provided (email/phone/company/notes)
    - defaults in config.json if CLI values are not provided

    This isolates the mapping logic so main() is easy to read.

    Returns:
    - dict {column_id: value} suitable for update_columns()
    """
    col_cfg = config["columns"]
    defaults = config.get("defaults", {})

    column_values: Dict[str, Any] = {}

    # Only set values if we have something meaningful to write
    if args.email:
        column_values[col_cfg["email"]] = args.email

    if args.phone:
        column_values[col_cfg["phone"]] = args.phone

    company_value = args.company if args.company is not None else defaults.get("company", "")
    if company_value:
        column_values[col_cfg["company"]] = company_value

    notes_value = args.notes if args.notes is not None else defaults.get("notes", "")
    if notes_value:
        column_values[col_cfg["notes"]] = notes_value

    return column_values


def main() -> None:
    """
    Program entrypoint.

    Flow:
    1) Load config.json
    2) Parse command-line args (client name required; other fields optional)
    3) Create a new item on the configured board/group
    4) Update the item's columns using provided info + defaults
    """
    config = load_config()

    parser = argparse.ArgumentParser(description="Create a client item in monday.com and fill in client info.")
    parser.add_argument("--client-name", required=True, help="Name of the client (this becomes the item name)")
    parser.add_argument("--email", default="", help="Client email")
    parser.add_argument("--phone", default="", help="Client phone")
    parser.add_argument("--company", default=None, help="Company name (overrides default in config.json)")
    parser.add_argument("--notes", default=None, help="Notes (overrides default in config.json)")

    args = parser.parse_args()

    board_cfg = config["board"]
    board_id = int(board_cfg["board_id"])
    group_id = board_cfg["group_id"]

    # Step 1: Create the client item
    item_id = create_item(board_id, group_id, args.client_name, config)
    print(f"[OK] Created item '{args.client_name}' with item_id={item_id}")

    # Step 2: Build and apply column updates
    column_values = build_column_values(args, config)

    if column_values:
        updated_id = update_columns(board_id, item_id, column_values, config)
        print(f"[OK] Updated item_id={updated_id} with columns={column_values}")
    else:
        print("[INFO] No column values to update (only created the item).")


if __name__ == "__main__":
    main()
